#!/bin/bash

# Test if user is root
[ "$USER" == "root" ] && echo "Dont run this as root" && exit


# Finds all files that are not README.md, install or belongs to the .git directory i.e. configuration files

# .surf, .surf/styles and .surf/styles/gruvbox-styles directories
mkdir ~/.surf
mkdir ~/.surf/styles
mkdir ~/.surf/styles/gruvbox-styles

find . 					\
		-type f			\
		! -name README.md 	\
      		! -name install   	\
      		! -path *.installfiles*   	\
		! -path '*.git*'	\
		-exec ".installfiles/copyconfig" {} \;
echo "Congratulations you now have my dotfiles!"
