#!/bin/bash

# Finds all files that are not README.md, install or belongs to the .git directory i.e. configuration files
find . 					\
		-type f			\
		! -name README.md 	\
       		! -name install   	\
		! -name renaming  	\
		! -path '*.git*'	\
		-exec """		\
		while true
		do
			read -p \"Do you want to install {} \" yn
			case $yn in
				[Yy]* ) break;;
				[Nn]* ) exit;;
				* ) echo \"Please answer yes or no. \";;
			esac
		done
			 	"""

