#!/bin/bash

# Usage copyconfig [configuration file]

ORIGIN=$1
DESTINATION=$(echo "$ORIGIN" | sed "s#^\./#$HOME/#")

if [ -a "$DESTINATION" ] # if destination exists
then
	while true
	do
		echo "$DESTINATION already exists."
		read -p "Do you want to overwrite it " yn
		case $yn in
			[Yy]* ) cp "$ORIGIN" "$DESTINATION"; break;;
			[Nn]* ) exit;;
		* ) echo \"Please answer yes or no. \";;
		esac
	done
fi
