#!/bin/bash

# Usage copyconfig [configuration file]

# Declare and initialize variables
ORIGIN=$1
DESTINATION=$(echo "$ORIGIN" | sed "s#^\./#$HOME/#")

# Checks if DESTINATION already exists.
if [ -a "$DESTINATION" ] # if destination exists
then
	# Checks if ORIGIN and DESTINATION is identical
	if diff "$ORIGIN" "$DESTINATION" > /dev/null 
	then
		echo "$DESTINATION is identical to $ORIGIN"
		exit
	fi

	while true
	do
		echo "$DESTINATION already exists."
		read -p "Do you want to overwrite it " yn
		case $yn in
			[Yy]* ) cp "$ORIGIN" "$DESTINATION"; break;;
			[Nn]* ) exit;;
		* ) echo \"Please answer yes or no. \";;
		esac
	done
else
	echo "Creating $DESTINATION"	
	cp "$ORIGIN" "$DESTINATION"
fi

